### ISSUE TITLE
Armed "Night" Error

### ISSUE THREAD

**Issue by 7RDR7** [lockpicker/homebridge-honeywell-tuxedo-touch#2]
When I select "Night" to arm the system, the system disarms itself and returns the following error.

[10/10/2020, 9:33:14 AM] [Home Security] Unknown alarm state: Armed Instant please report this through a github issue to the developer
[10/10/2020, 9:33:14 AM] [Home Security] Polling noticed target state change to 3, notifying devices

The plugin does not appear to understand "Armed Instant", which is our "Night" state. The "Armed Instant" mode eliminates the enter delay.

**Comment by 7RDR7** [comment]
Issue resolved. Disabled authentication on the Tuxedo. All working well. Thanks for the great plugin!

**Comment by lockpicker** [comment]
Thanks for flagging. There's no good API spec for the Honeywell tuxedo unit that I've been able to find so the state mappings are based on what I and a bunch of friends with the same system have on our units. 
Have added the "Armed Instant" state to pick up another version of night mode. See if this fixes your issue.

**Comment by 7RDR7** [comment]
Thanks Ashish! That did it!

**Comment by lockpicker** [comment]
Glad it worked for you. Cheers.
